# Generated by Django 3.2.17 on 2023-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banknifty', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=30)),
                ('Open', models.CharField(max_length=30)),
                ('High', models.CharField(max_length=30)),
                ('Low', models.CharField(max_length=30)),
                ('Close', models.CharField(max_length=30)),
                ('Volume', models.CharField(max_length=30)),
            ],
        ),
    ]
