# Generated by Django 3.2.17 on 2023-03-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_candles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candles',
            name='Banknifty',
        ),
        migrations.RemoveField(
            model_name='candles',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='candles',
            name='Volume',
        ),
    ]
